export const Cropnames = [
    "Arecanut",
    "Arhar/Tur",
    "Banana",
    "Black pepper",
    "Cashewnut",
    "Coconut ",
    "Cowpea(Lobia)",
    "Dry chillies",
    "Ginger",
    "Groundnut",
    "Maize",
    "Moong(Green Gram)",
    "Oilseeds total",
    "Other Kharif pulses",
    "Rapeseed &Mustard",
    "Rice",
    "Sesamum",
    "Sugarcane",
    "Sunflower",
    "Sweet potato",
    "Tapioca",
    "Turmeric",
    "Urad",
    "other oilseeds",
    "Bajra",
    "Castor seed",
    "Coriander",
    "Cotton(lint)",
    "Garlic",
    "Gram",
    "Guar seed",
    "Horse-gram",
    "Jowar",
    "Linseed",
    "Masoor",
    "Mesta",
    "Niger seed",
    "Onion",
    "Other  Rabi pulses",
    "Potato",
    "Ragi",
    "Safflower",
    "Small millets",
    "Soyabean",
    "Tobacco",
    "Wheat",
    "Peas & beans (Pulses)",
    "Jute",
    "Barley",
    "Khesari",
    "Sannhamp",
    "Moth",
    "Other Cereals",
    "Cardamom",
    "Other Summer Pulses"
]

export const States = [
    "Andaman and Nicobar Island",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "CHANDIGARH",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "THE DADRA AND NAGAR HAVELI",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
]

export const District = [
    "BAKSA",
    "BARPETA",
    "BISWANATH\n",
    "BONGAIGAON",
    "CACHAR",
    "CHARAIDEO\n",
    "CHIRANG",
    "DARRANG",
    "DHEMAJI",
    "DHUBRI",
    "DIBRUGARH",
    "DIMA HASAO",
    "GOALPARA",
    "GOLAGHAT",
    "HAILAKANDI",
    "HOJAI\n",
    "JORHAT",
    "KAMRUP",
    "KAMRUP METRO",
    "KARBI ANGLONG",
    "KARIMGANJ",
    "KOKRAJHAR",
    "LAKHIMPUR",
    "MAJULI\n",
    "MARIGAON",
    "NAGAON",
    "NALBARI",
    "SIVASAGAR",
    "SONITPUR",
    "SOUTH SALMARA MANCACHAR\n",
    "TINSUKIA",
    "UDALGURI",
    "WEST KARBI ANGLONG\n"
]

export const Seasons = [
    "Autumn",
    "Kharif",
    "Rabi",
    "Summer",
    "Whole Year",
    "Winter"
]
